services:
  front:
    build: front
    image: silmaril-front
    ports:
      - 4200:80
  api:
    build: api
    image: silmaril-api
    ports:
      - 5000:5000
    depends_on:
      migrator:
        condition: service_completed_successfully
    environment:
      - ConnectionStrings__PostgreSql=Host=db;Port=5432;Database=silmaril;Username=userpg;Password=root;
  db:
    image: postgres:18.3
    environment:
      - POSTGRES_DB=silmaril
      - POSTGRES_USER=userpg
      - POSTGRES_PASSWORD=root
    ports:
      - 5431:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h 127.0.0.1 -p 5432 -U userpg -d silmaril || exit 1"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
  migrator:
    build:
      context: api
      dockerfile: Dockerfile.migrator
    image: silmaril-migrator
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ConnectionStrings__PostgreSql=Host=db;Port=5432;Database=silmaril;Username=userpg;Password=root;