export const simpleWords = [
    'cat', 'dog', 'bird', 'fish', 'tree', 'book', 'red', 'blue', 'sun', 'moon', 'star',
    'fire', 'rock', 'wind', 'rain', 'snow', 'leaf', 'cloud', 'frog', 'bear', 'lion', 'wolf', 'ant', 'bee', 'bat', 'owl', 'fox', 'cow', 'pig', 'rat', 'hen',
    'cup', 'pen', 'key', 'box', 'car', 'bus', 'van', 'jet', 'sky', 'sea', 'lake', 'pond',
    'hill', 'path', 'road', 'door', 'wall', 'roof', 'farm', 'barn', 'yard', 'park', 'play',
    'walk', 'run', 'jump', 'swim', 'read', 'sing', 'song', 'tree', 'wood', 'seed', 'root',
    'leaf', 'rose', 'tulip', 'daisy', 'lily', 'cafe', 'food', 'milk', 'cake', 'salt', 'soup',
    'rice', 'fish', 'meat', 'bird', 'ant', 'cow', 'dog', 'cat', 'rat', 'bat',
    'egg', 'oil', 'tea', 'jam', 'pie', 'pot', 'pan', 'cup', 'lid', 'bin', 'mat', 'rug', 'bed',
    'box', 'bag', 'hat', 'cap', 'sun', 'sky', 'sea', 'ice', 'mud', 'wax', 'web', 'net', 'zip',
    'key', 'log', 'map', 'toy', 'car', 'bus', 'jet', 'cab', 'taxi', 'bike', 'boat', 'baton', 'crab', 'duck', 'deer', 'pup', 'ape', 'ram', 'yak', 'cub',
    'jar', 'bun', 'tap', 'fan', 'tin', 'pad', 'nap', 'gem', 'peg',
    'tab', 'sack', 'can', 'hub', 'tug', 'mug', 'zap',
    'gap', 'tag', 'nab', 'hug', 'buzz', 'pop', 'snap',
    'crab', 'duck', 'deer', 'pup', 'ape', 'ram', 'yak', 'cub', 'jar', 'bun',
    'tap', 'fan', 'tin', 'pad', 'nap', 'gem', 'peg', 'tab', 'sack', 'can',
    'hub', 'tug', 'mug', 'zap', 'gap', 'tag', 'nab', 'hug', 'buzz', 'pop', 'twig', 'den', 'nest', 'bark', 'reef', 'fern', 'drum',
    'camp', 'tent', 'pond', 'swamp', 'trap', 'dash', 'rash', 'rash', 'mash',
    'snag', 'snub', 'grub', 'palm', 'ramp', 'puff', 'snag', 'bash', 'pack',
    'rack', 'tack', 'peck', 'deck', 'beak', 'crag', 'twig', 'brag', 'gasp',
    'grab', 'stab', 'yap', 'perk', 'perk', 'rung', 'bung', 'pest', 'pact',
    'fact', 'tract', 'vast', 'cast', 'past', 'task', 'husk', 'dusk', 'rust',
    'mask', 'flap', 'clap', 'trap', 'yarn', 'peep', 'beep', 'deep',
    'creep', 'jeep', 'bump', 'stump', 'camp', 'fuzz',

    'hobbit', 'shire', 'gandalf', 'frodo', 'samwise', 'aragorn', 'legolas', 'gimli', 'boromir',
    'sauron', 'mordor', 'rivendell', 'gollum', 'balrog', 'elf', 'dwarf', 'orc', 'ring', 'ent',
    'rohan', 'isengard', 'mithril', 'galadriel', 'saruman', 'elfstone', 'numenor', 'anduril',
    'barad-dur', 'pelennor', 'urgal', 'lothlorien', 'shirefolk', 'warg', 'troll', 'oden',
    'beren', 'melkor', 'valar', 'maiar', 'eowyn', 'faramir', 'glorfindel', 'silmaril', 'eldar',
    'durin', 'noldor', 'dunedain', 'gwaith', 'ithilien', 'angmar', 'turin', 'hurin', 'morwen',
    'beleg', 'feanor', 'fingolfin', 'finrod', 'tulkas', 'ulmo', 'manwe', 'yavanna', 'mandos',
    'nerevar', 'tinuviel', 'elbereth', 'earendil', 'melian', 'namarie', 'celebrimbor', 'earendil',
    'gil-galad', 'ancalagon', 'maeglin', 'thalion', 'thorondor', 'glaurung', 'varda', 'nienna',
    'mandos', 'luthien', 'beleriand', 'feanorian', 'ornament', 'silmarils', 'angband', 'dagor',
    'nargothrond', 'dol-guldur', 'mirrormere', 'telerin', 'aeglos', 'rohirrim', 'glorfindel',
    'morgoth', 'gondolin', 'helcaraxe', 'noldorin', 'valinor', 'tol-in-galduroth', 'aegnor',
    'finwe', 'fingon', 'galathilion', 'haldir', 'hithlum', 'lothlann', 'gorthaur', 'annatar',
    'narsil', 'vilya', 'narya'
];