FROM mcr.microsoft.com/dotnet/sdk:8.0 AS migrator
WORKDIR /src
COPY ./Api/*.csproj ./Api/
RUN dotnet restore ./Api/Api.csproj
COPY . ./
RUN dotnet tool install --global dotnet-ef
ENV PATH="${PATH}:/root/.dotnet/tools"
RUN chmod +x ./Api/entrypoint.migrator.sh
WORKDIR /src/Api
CMD ["./entrypoint.migrator.sh"]

